[package]
name = "repo-notify"
version = "0.1.0"
authors = ["Kyle Deal <kdeal@kyledeal.com>"]

[dependencies]
github-rs = "0.5"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0"
toml = "0.4"
