[package]
name = "repo-notify"
version = "0.1.0"
authors = ["Kyle Deal <kdeal@kyledeal.com>"]

[dependencies]
clap = "2"
github-rs = "0.5"
rpassword = "1.0.0"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0"
reqwest = "0.7.3"
toml = "0.4"
text_io = "0.1.6"
